title:            City as Campus
description:      Open source project for city-based learning hub
url:              # Site url.
signoff:          # Your name.
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )

links:
  - name:         About
    url:          /about
  - name:         GitHub
    url:          http://github.com/saxifrage/learn
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
